# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vE6U80hp4EU6HFT4LShN5Znckj8lwUI5
"""

import os
import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image
import gradio as gr
from groq import Groq

device = "cuda" if torch.cuda.is_available() else "cpu"

# ---------- Load backbone ----------
backbone = models.efficientnet_b0(weights=models.EfficientNet_B0_Weights.IMAGENET1K_V1)
feat_dim = backbone.classifier[1].in_features
backbone.classifier = nn.Identity()
backbone = backbone.to(device).eval()

# ---------- Load heads ----------
class_head = nn.Sequential(
    nn.Linear(feat_dim, 128), nn.ReLU(), nn.Dropout(0.3), nn.Linear(128, 4)
).to(device)
class_head.load_state_dict(torch.load("class_head.pth", map_location=device))
class_head.eval()

severity_head = nn.Sequential(
    nn.Linear(feat_dim, 64), nn.ReLU(), nn.Dropout(0.4), nn.Linear(64, 4)
).to(device)
severity_head.load_state_dict(torch.load("severity_head.pth", map_location=device))
severity_head.eval()

SKIN_TYPES = ["combination", "dry", "normal", "oily"]  # must match training class order
SEVERITY_LABELS = ["acne", "redness", "oiliness", "wrinkles"]

eval_tfms = transforms.Compose([
    transforms.Resize((160, 160)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])

# ---------- Groq client ----------
groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

# ---------- Guardrails ----------
def input_guardrail(user_message: str):
    blocked_patterns = [
        "ignore previous", "ignore your instructions", "system prompt",
        "you are now", "act as", "jailbreak", "diagnose me with",
        "prescribe", "what medication"
    ]
    lowered = user_message.lower()
    for pattern in blocked_patterns:
        if pattern in lowered:
            return False, f"Message flagged by guardrail (matched: '{pattern}')"
    return True, ""

def output_guardrail(routine_text: str):
    risky_phrases = ["you have", "diagnosed with", "this confirms", "definitely acne", "definitely rosacea"]
    lowered = routine_text.lower()
    for phrase in risky_phrases:
        if phrase in lowered:
            return False, ("I can't provide a diagnosis. Based on the scan, here's general guidance — "
                            "please consult a dermatologist for anything persistent or severe.")
    if "not a medical diagnosis" not in lowered:
        routine_text += "\n\n*This is general guidance, not a medical diagnosis. Consult a dermatologist for persistent or severe concerns.*"
    return True, routine_text

# ---------- Core pipeline ----------
@torch.no_grad()
def analyze_face(image: Image.Image):
    img_t = eval_tfms(image.convert("RGB")).unsqueeze(0).to(device)
    feats = backbone(img_t)

    skin_type_probs = torch.softmax(class_head(feats), dim=1)[0]
    predicted_type = SKIN_TYPES[skin_type_probs.argmax().item()]
    type_confidence = skin_type_probs.max().item()

    severity_scores = severity_head(feats)[0].clamp(0, 5).cpu().numpy()
    severity_dict = {label: round(float(s), 1) for label, s in zip(SEVERITY_LABELS, severity_scores)}

    return {"skin_type": predicted_type, "skin_type_confidence": round(type_confidence, 2), "severity": severity_dict}

def generate_routine(analysis):
    system_prompt = """You are a skincare routine assistant. You are NOT a dermatologist and must never make medical diagnoses or claims.

Given a skin type and severity scores (0-5 scale, where 5 is most severe) for acne, redness, oiliness, and wrinkles, generate:
1. A short, friendly 1-2 sentence summary of what the scores suggest
2. A simple AM/PM skincare routine (3-4 steps each, general product categories only, not brand names)
3. One sentence on when to see a dermatologist, only if severity for acne or redness is 3 or higher

Always end with: "This is general guidance, not a medical diagnosis. Consult a dermatologist for persistent or severe concerns."

Keep the tone warm and practical. Do not use definitive diagnostic language like "you have acne" — use "your scan suggests mild acne-prone tendencies" instead."""

    user_prompt = f"""Skin type: {analysis['skin_type']}
Severity scores (0-5): acne={analysis['severity']['acne']}, redness={analysis['severity']['redness']}, oiliness={analysis['severity']['oiliness']}, wrinkles={analysis['severity']['wrinkles']}"""

    response = groq_client.chat.completions.create(
        model="openai/gpt-oss-120b",
        messages=[{"role": "system", "content": system_prompt}, {"role": "user", "content": user_prompt}],
        temperature=0.7,
        max_tokens=700
    )
    return response.choices[0].message.content

def safe_generate_routine(analysis, user_message="face scan analysis"):
    is_safe, reason = input_guardrail(user_message)
    if not is_safe:
        return f"⚠️ Request blocked: {reason}"
    routine_text = generate_routine(analysis)
    _, final_text = output_guardrail(routine_text)
    return final_text

def full_pipeline(image):
    if image is None:
        return "Please upload a photo to get started."
    analysis = analyze_face(image)
    routine = safe_generate_routine(analysis)
    summary = (
        f"**Detected skin type:** {analysis['skin_type']} (confidence: {analysis['skin_type_confidence']*100:.0f}%)\n\n"
        f"**Severity scores (0–5):** Acne {analysis['severity']['acne']} · "
        f"Redness {analysis['severity']['redness']} · Oiliness {analysis['severity']['oiliness']} · "
        f"Wrinkles {analysis['severity']['wrinkles']}\n\n---\n\n{routine}"
    )
    return summary

# ---------- UI ----------
with gr.Blocks(title="Kamal — AI Skin & Hair Expert") as demo:
    gr.Markdown(
        """
        <div style="text-align: center;">
            <h1>🪷 Kamal</h1>
            <p style="font-size: 1.1em; color: #666;">Your AI Skin & Hair Expert</p>
        </div>
        """
    )
    gr.Markdown(
        "Upload a photo to get an AI-estimated skin-type and severity analysis, plus a personalized skincare routine.\n\n"
        "⚠️ **This is a portfolio/demo project, not a medical tool.** Results are from a small model trained on a "
        "limited dataset and should not be used for real skincare or medical decisions."
    )
    with gr.Row():
        image_input = gr.Image(type="pil", label="Upload a clear, front-facing photo")
        output_md = gr.Markdown(label="Your Analysis & Routine")
    submit_btn = gr.Button("Analyze", variant="primary")
    submit_btn.click(fn=full_pipeline, inputs=image_input, outputs=output_md)

if __name__ == "__main__":
    demo.launch()